//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HydroAnalyzer_v0._4
{
    using System;
    using System.Collections.Generic;
    
    public partial class hyddnev
    {
        public int Station { get; set; }
        public System.DateTime Dat { get; set; }
        public Nullable<int> Stoej { get; set; }
        public string CodH { get; set; }
        public string CodQ { get; set; }
        public string Temp { get; set; }
    }
}
