//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HydroAnalyzer_v0._4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChartEntities : DbContext
    {
        public ChartEntities()
            : base("name=ChartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<hyddnev> hyddnevs { get; set; }
        public DbSet<hydgod> hydgods { get; set; }
        public DbSet<hydme> hydmes { get; set; }
        public DbSet<user> users { get; set; }
    }
}
